fixed compilation error
std::pair is defined with int argument first, float argument second.

Error message:
fatal error: implicit conversion from 'double' to 'int' changes value from 5.1 to 5